// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import java.lang.String;

privileged aspect BookCategory_Roo_JavaBean {
    
    public String BookCategory.getCategory() {
        return this.category;
    }
    
    public void BookCategory.setCategory(String category) {
        this.category = category;
    }
    
}
