// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import com.max.bookstore.model.People;

privileged aspect Book_Roo_JavaBean {
    
    public People Book.getOwner() {
        return this.owner;
    }
    
    public void Book.setOwner(People owner) {
        this.owner = owner;
    }
    
}
