// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import com.max.bookstore.model.BorrowCardDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BorrowCardIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BorrowCardIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BorrowCardIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BorrowCardIntegrationTest: @Transactional;
    
    @Autowired
    private BorrowCardDataOnDemand BorrowCardIntegrationTest.dod;
    
    @Test
    public void BorrowCardIntegrationTest.testCountBorrowCards() {
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", dod.getRandomBorrowCard());
        long count = com.max.bookstore.model.BorrowCard.countBorrowCards();
        org.junit.Assert.assertTrue("Counter for 'BorrowCard' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BorrowCardIntegrationTest.testFindBorrowCard() {
        com.max.bookstore.model.BorrowCard obj = dod.getRandomBorrowCard();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to provide an identifier", id);
        obj = com.max.bookstore.model.BorrowCard.findBorrowCard(id);
        org.junit.Assert.assertNotNull("Find method for 'BorrowCard' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'BorrowCard' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BorrowCardIntegrationTest.testFindAllBorrowCards() {
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", dod.getRandomBorrowCard());
        long count = com.max.bookstore.model.BorrowCard.countBorrowCards();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'BorrowCard', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.max.bookstore.model.BorrowCard> result = com.max.bookstore.model.BorrowCard.findAllBorrowCards();
        org.junit.Assert.assertNotNull("Find all method for 'BorrowCard' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'BorrowCard' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BorrowCardIntegrationTest.testFindBorrowCardEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", dod.getRandomBorrowCard());
        long count = com.max.bookstore.model.BorrowCard.countBorrowCards();
        if (count > 20) count = 20;
        java.util.List<com.max.bookstore.model.BorrowCard> result = com.max.bookstore.model.BorrowCard.findBorrowCardEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'BorrowCard' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'BorrowCard' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BorrowCardIntegrationTest.testFlush() {
        com.max.bookstore.model.BorrowCard obj = dod.getRandomBorrowCard();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to provide an identifier", id);
        obj = com.max.bookstore.model.BorrowCard.findBorrowCard(id);
        org.junit.Assert.assertNotNull("Find method for 'BorrowCard' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBorrowCard(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'BorrowCard' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BorrowCardIntegrationTest.testMerge() {
        com.max.bookstore.model.BorrowCard obj = dod.getRandomBorrowCard();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to provide an identifier", id);
        obj = com.max.bookstore.model.BorrowCard.findBorrowCard(id);
        boolean modified =  dod.modifyBorrowCard(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.max.bookstore.model.BorrowCard merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'BorrowCard' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BorrowCardIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", dod.getRandomBorrowCard());
        com.max.bookstore.model.BorrowCard obj = dod.getNewTransientBorrowCard(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'BorrowCard' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'BorrowCard' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BorrowCardIntegrationTest.testRemove() {
        com.max.bookstore.model.BorrowCard obj = dod.getRandomBorrowCard();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BorrowCard' failed to provide an identifier", id);
        obj = com.max.bookstore.model.BorrowCard.findBorrowCard(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'BorrowCard' with identifier '" + id + "'", com.max.bookstore.model.BorrowCard.findBorrowCard(id));
    }
    
}
