// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import com.max.bookstore.model.PeopleDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PeopleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PeopleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PeopleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PeopleIntegrationTest: @Transactional;
    
    @Autowired
    private PeopleDataOnDemand PeopleIntegrationTest.dod;
    
    @Test
    public void PeopleIntegrationTest.testCountPeoples() {
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", dod.getRandomPeople());
        long count = com.max.bookstore.model.People.countPeoples();
        org.junit.Assert.assertTrue("Counter for 'People' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PeopleIntegrationTest.testFindPeople() {
        com.max.bookstore.model.People obj = dod.getRandomPeople();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to provide an identifier", id);
        obj = com.max.bookstore.model.People.findPeople(id);
        org.junit.Assert.assertNotNull("Find method for 'People' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'People' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PeopleIntegrationTest.testFindAllPeoples() {
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", dod.getRandomPeople());
        long count = com.max.bookstore.model.People.countPeoples();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'People', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.max.bookstore.model.People> result = com.max.bookstore.model.People.findAllPeoples();
        org.junit.Assert.assertNotNull("Find all method for 'People' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'People' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PeopleIntegrationTest.testFindPeopleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", dod.getRandomPeople());
        long count = com.max.bookstore.model.People.countPeoples();
        if (count > 20) count = 20;
        java.util.List<com.max.bookstore.model.People> result = com.max.bookstore.model.People.findPeopleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'People' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'People' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PeopleIntegrationTest.testFlush() {
        com.max.bookstore.model.People obj = dod.getRandomPeople();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to provide an identifier", id);
        obj = com.max.bookstore.model.People.findPeople(id);
        org.junit.Assert.assertNotNull("Find method for 'People' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPeople(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'People' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PeopleIntegrationTest.testMerge() {
        com.max.bookstore.model.People obj = dod.getRandomPeople();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to provide an identifier", id);
        obj = com.max.bookstore.model.People.findPeople(id);
        boolean modified =  dod.modifyPeople(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.max.bookstore.model.People merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'People' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PeopleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", dod.getRandomPeople());
        com.max.bookstore.model.People obj = dod.getNewTransientPeople(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'People' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'People' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PeopleIntegrationTest.testRemove() {
        com.max.bookstore.model.People obj = dod.getRandomPeople();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'People' failed to provide an identifier", id);
        obj = com.max.bookstore.model.People.findPeople(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'People' with identifier '" + id + "'", com.max.bookstore.model.People.findPeople(id));
    }
    
}
