// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import com.max.bookstore.model.People;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PeopleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PeopleDataOnDemand: @Component;
    
    private Random PeopleDataOnDemand.rnd = new SecureRandom();
    
    private List<People> PeopleDataOnDemand.data;
    
    public People PeopleDataOnDemand.getNewTransientPeople(int index) {
        People obj = new People();
        setEmail(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void PeopleDataOnDemand.setEmail(People obj, int index) {
        String email = "email_" + index;
        obj.setEmail(email);
    }
    
    public void PeopleDataOnDemand.setName(People obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public People PeopleDataOnDemand.getSpecificPeople(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        People obj = data.get(index);
        return People.findPeople(obj.getId());
    }
    
    public People PeopleDataOnDemand.getRandomPeople() {
        init();
        People obj = data.get(rnd.nextInt(data.size()));
        return People.findPeople(obj.getId());
    }
    
    public boolean PeopleDataOnDemand.modifyPeople(People obj) {
        return false;
    }
    
    public void PeopleDataOnDemand.init() {
        data = People.findPeopleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'People' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.max.bookstore.model.People>();
        for (int i = 0; i < 10; i++) {
            People obj = getNewTransientPeople(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
