// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import com.max.bookstore.model.BorrowCard;
import com.max.bookstore.model.Status;
import java.lang.Boolean;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect StatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StatusDataOnDemand: @Component;
    
    private Random StatusDataOnDemand.rnd = new SecureRandom();
    
    private List<Status> StatusDataOnDemand.data;
    
    public Status StatusDataOnDemand.getNewTransientStatus(int index) {
        Status obj = new Status();
        setBorrowCard(obj, index);
        setCanBorrow(obj, index);
        return obj;
    }
    
    public void StatusDataOnDemand.setBorrowCard(Status obj, int index) {
        BorrowCard borrowCard = null;
        obj.setBorrowCard(borrowCard);
    }
    
    public void StatusDataOnDemand.setCanBorrow(Status obj, int index) {
        Boolean canBorrow = Boolean.TRUE;
        obj.setCanBorrow(canBorrow);
    }
    
    public Status StatusDataOnDemand.getSpecificStatus(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Status obj = data.get(index);
        return Status.findStatus(obj.getId());
    }
    
    public Status StatusDataOnDemand.getRandomStatus() {
        init();
        Status obj = data.get(rnd.nextInt(data.size()));
        return Status.findStatus(obj.getId());
    }
    
    public boolean StatusDataOnDemand.modifyStatus(Status obj) {
        return false;
    }
    
    public void StatusDataOnDemand.init() {
        data = Status.findStatusEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Status' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.max.bookstore.model.Status>();
        for (int i = 0; i < 10; i++) {
            Status obj = getNewTransientStatus(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
