// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.max.bookstore.model;

import com.max.bookstore.model.StatusDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StatusIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: StatusIntegrationTest: @Transactional;
    
    @Autowired
    private StatusDataOnDemand StatusIntegrationTest.dod;
    
    @Test
    public void StatusIntegrationTest.testCountStatuses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", dod.getRandomStatus());
        long count = com.max.bookstore.model.Status.countStatuses();
        org.junit.Assert.assertTrue("Counter for 'Status' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StatusIntegrationTest.testFindStatus() {
        com.max.bookstore.model.Status obj = dod.getRandomStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to provide an identifier", id);
        obj = com.max.bookstore.model.Status.findStatus(id);
        org.junit.Assert.assertNotNull("Find method for 'Status' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Status' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StatusIntegrationTest.testFindAllStatuses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", dod.getRandomStatus());
        long count = com.max.bookstore.model.Status.countStatuses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Status', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.max.bookstore.model.Status> result = com.max.bookstore.model.Status.findAllStatuses();
        org.junit.Assert.assertNotNull("Find all method for 'Status' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Status' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StatusIntegrationTest.testFindStatusEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", dod.getRandomStatus());
        long count = com.max.bookstore.model.Status.countStatuses();
        if (count > 20) count = 20;
        java.util.List<com.max.bookstore.model.Status> result = com.max.bookstore.model.Status.findStatusEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Status' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Status' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StatusIntegrationTest.testFlush() {
        com.max.bookstore.model.Status obj = dod.getRandomStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to provide an identifier", id);
        obj = com.max.bookstore.model.Status.findStatus(id);
        org.junit.Assert.assertNotNull("Find method for 'Status' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStatus(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Status' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatusIntegrationTest.testMerge() {
        com.max.bookstore.model.Status obj = dod.getRandomStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to provide an identifier", id);
        obj = com.max.bookstore.model.Status.findStatus(id);
        boolean modified =  dod.modifyStatus(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.max.bookstore.model.Status merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Status' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StatusIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", dod.getRandomStatus());
        com.max.bookstore.model.Status obj = dod.getNewTransientStatus(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Status' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Status' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StatusIntegrationTest.testRemove() {
        com.max.bookstore.model.Status obj = dod.getRandomStatus();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Status' failed to provide an identifier", id);
        obj = com.max.bookstore.model.Status.findStatus(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Status' with identifier '" + id + "'", com.max.bookstore.model.Status.findStatus(id));
    }
    
}
